### ISSUE TITLE
Prebuilt binaries looking for Python 3.7

### ISSUE THREAD

**Issue by jangrewe** [hissingshark/hyperion-vero4k#3]
I just reinstalled my Vero 4K+ and wanted to get Hyperion on there again, so i used the prebuilt binaries - but they don't start:

```
Jan 10 17:13:05 nukebox systemd[1]: Started Hyperion ambient light systemd service  for user osmc.
Jan 10 17:13:05 nukebox hyperiond[9633]: /usr/bin/hyperiond: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
Jan 10 17:13:05 nukebox systemd[1]: hyperion.service: Main process exited, code=exited, status=127/n/a
```

I guess you updated `install.sh`, but not the prebuilt binaries? ;-) 
https://github.com/hissingshark/hyperion-vero4k/commit/ac549f13fbf3913ad981cc5b26541f02a6ada1f8

**Comment by hissingshark** [comment]
You may have been right.  Updated to 2.0.15 now.
