### ISSUE TITLE
Missing python libraries for building from source

### ISSUE THREAD

**Issue by gymnae** [hissingshark/hyperion-vero4k#4]
Not 100% sure, but I think I needed to install a couple of more python libraries to be able to build on my fully updated (Feb 23) vero4k:

1. jsonschema
2. jinja2

I installed those via `sudo pip3 install <library>`

**Comment by hissingshark** [comment]
As per forum - updated to 2.0.15.
The only issue was you were building an older version, rather then specifying something current. e.g.
`sudo ./install master
`
or
`sudo ./install 24a00e3`

The python libraries don't seem to be relevant, at least not on my system,
